### ISSUE TITLE
dependancies: "npm install" fails on pulling @AlCalzone node-aead-crypto

### ISSUE THREAD

**Issue by afleuryg** [fvanwijk/tradfri-app#3]
Hi,
While trying to install, I got this bunch of errors:

```npm-script
node-pre-gyp ERR! Tried to download(404): https://github.com/AlCalzone/node-aead-crypto/releases/download/v1.0.2/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-aead-crypto@1.0.2 and node@14.16.0 (node-v83 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/AlCalzone/node-aead-crypto/releases/download/v1.0.2/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-aead-crypto@1.0.2 and node@14.16.0 (node-v83 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(325,5): error MSB3371: The file "Release\obj\node_aead_crypto\node_aead
_crypto.tlog\unsuccessfulbuild" cannot be created. The process cannot access the file 'C:\Users\AFG\Desktop\tradfri-app-master\node_modules\node-aead-crypto\build\Release\obj\node_aead_c
rypto\node_aead_crypto.tlog\unsuccessfulbuild' because it is being used by another process. [C:\Users\AFG\Desktop\tradfri-app-master\node_modules\node-aead-crypto\build\node_aead_crypto.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
```

From my current ignorance, I see 2 possibilities:
- @AlCalzone changed/deleted its repository (changed the name ?)
- I may have to update Visual Studio to the latest version

There is a third possibility: I didn't understand something.

Any idea?
Thanks in advance for any help...
   A.

**Comment by AlCalzone** [comment]
> because it is being used by another process

I think this has to do with the build process. The repo is also definitely there: https://github.com/AlCalzone/node-aead-crypto/

But it seems like you don't need `node-aead-crypto` anyways, that's only needed for Node.js <10
I suggest adding it as an optional dependency with the latest version. This causes it to only be installed if necessary.
See https://github.com/AlCalzone/node-dtls-client/blob/df4477b56b399b17679643ab2e7ea2367ebe68d3/package.json#L44 and https://github.com/AlCalzone/node-dtls-client/blob/master/src/lib/AEADCrypto.ts for details.
